### PR TITLE
Upgrade package to be compatible with Flow 4.* LTS

### PR DESCRIPTION
**Pull request by svparijs**
Did several fixes to make this package compatible with Flow 4.*. Verified the changes and would like to merge this into the main source for other to enjoy.

### CODE REVIEW

**Comment by kaystrobach** [comment]
thank you for your contribution, will evaluate it in the next days.

I'm currently working on a followup project, which is able to do the same task, without using flow.
Will add more information into the readme soon.

**Comment by svparijs** [comment]
Our application is Flow based so the current integration is sufficient. Thanks in advance for the effort.

**Comment by kaystrobach** [comment]
Sure, the followup will use the same seen from the cli, as there will be a flow wrapper 😉

But there will be also one for TYPO3 and other frameworks.

**Comment by kaystrobach** [comment]
you can use version 1.x now 👍

**Pull request merged**
